run:
  tests: false
  timeout: 10m

linters: 
  disable-all: true
  enable:
    - misspell
    - gofmt
    - goimports
    - ineffassign
    - revive
    - unconvert
    - unused
    - govet

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
  max-issues-per-linter: 0
  max-same-issues: 0
