version: "2"

run:
  modules-download-mode: vendor
  tests: false

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - revive
    - unconvert
    - unused
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: "(unused-parameter|redefines-builtin-id):"
    # Log a warning if an exclusion rule is unused.
    # Default: false
    warn-unused: true

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
