version: "2"

run:
  tests: true
  timeout: 10m

linters: 
  default: none
  enable:
    - ginkgolinter
    - govet
    - ineffassign
    - misspell
    - modernize
    - revive
    - unconvert
    - unused
  settings:
    govet:
      enable:
        - nilness
    revive:
      enable-default-rules: true
      max-open-files: 2048
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - ineffassign
          - misspell
          - revive
          - unused
        path: .*_test.go
    paths:
      - .*\.pb\.go$
    warn-unused: true

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    warn-unused: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
