version: "2"

run:
  tests: false
  timeout: 10m

linters: 
  default: none
  enable:
    - ginkgolinter
    - gocritic
    - govet
    - ineffassign
    - misspell
    - modernize
    - revive
    - unconvert
    - unused
  settings:
    gocritic:
      disabled-checks:
        - appendAssign
        - appendCombine
        - assignOp
        - badLock
        - builtinShadow
        - commentedOutCode
        - deferInLoop
        - emptyStringTest
        - evalOrder
        - exposedSyncMutex
        - hugeParam
        - importShadow
        - nestingReduce
        - nilValReturn
        - octalLiteral
        - paramTypeCombine
        - rangeValCopy
        - regexpSimplify
        - singleCaseSwitch
        - sloppyReassign
        - typeAssertChain
        - unlabelStmt
        - unlambda
        - unnamedResult
        - whyNoLint
        - yodaStyleExpr
      enable-all: true
    govet:
      enable:
        - nilness
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: stutters
      - linters:
          - revive
        text: empty-block
      - linters:
          - revive
        text: superfluous-else
      - linters:
          - revive
        text: unused-parameter
      - linters:
          - revive
        text: redefines-builtin-id
      - linters:
          - revive
        text: if-return
    paths:
      - .*\.pb\.go$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
