run:
  tests: false
  timeout: 10m
linters: 
  disable-all: true
  enable:
    - errorlint
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - revive
    - unconvert
    - unused
