# Base path used to install.
DESTDIR=/usr/local

# Used to populate version variable in main package.
VERSION=$(shell git describe --match 'v[0-9]*' --dirty='.m' --always)

# Race detector is only supported on amd64.
RACE := $(shell test $$(go env GOARCH) != "amd64" || (echo "-race"))

# Project packages.
PACKAGES = $(shell go list ./...)
INTEGRATION_PACKAGE = $(shell go list ./integration)

# Project binaries.
COMMANDS=swarm-bench protoc-gen-goswarm proto-name-fix
BINARIES=$(addprefix bin/,$(COMMANDS))
SWARMD_COMMANDS=swarmd swarmctl swarm-rafttool
SWARMD_BINARIES=$(addprefix swarmd/bin/,$(SWARMD_COMMANDS))

VERSIONPKG := $(shell go list ./version)
GO_LDFLAGS=-ldflags "-X $(VERSIONPKG).Version=$(VERSION)"
GO_TESTFLAGS=--timeout=20m $(RACE)

GOBIN=$(shell go env GOPATH)/bin

.DEFAULT_GOAL = all
.PHONY: all
all: check binaries test integration-tests swarmd-tests ## run check, build the binaries and run the tests

.PHONY: ci
ci: check binaries checkprotos coverage coverage-integration ## to be used by the CI

.PHONY: AUTHORS
AUTHORS: .mailmap .git/HEAD
	git log --format='%aN <%aE>' | sort -fu > $@

# This only needs to be generated by hand when cutting full releases.
version/version.go:
	./version/version.sh > $@

.PHONY: setup
setup: ## install dependencies
	@echo "🐳 $@"
	# install golangci-lint to ./bin/golangci-lint
	@curl -fsSL https://raw.githubusercontent.com/golangci/golangci-lint/v2.1.5/install.sh | sh -s v2.1.5
	# install standard protobuf code generators (pinned for reproducible codegen)
	@go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11
	@go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.6.2

.PHONY: generate
generate: protos
	@echo "🐳 $@"
	@PATH=${ROOTDIR}/bin:${GOBIN}:${PATH} go generate -x ${PACKAGES}

# API protos get the full treatment (go + grpc + goswarm). plugin.proto is an
# options-definition file (analogous to descriptor.proto) and is generated
# separately with protoc-gen-go only — it must not receive the swarmkit codegen
# plugins (deepcopy/storeobject/raftproxy/authwrapper).
PROTO_SRCS = $(wildcard api/*.proto)
# Include paths: project root, system protobuf includes, and vendor (for the
# etcd raftpb proto that api/raft.proto imports).
PROTO_INCLUDES = -I. -I/usr/local/include -Ivendor

# Map well-known types, our plugin, and API protos to the correct Go packages.
# These -M flags are passed to protoc-gen-go, protoc-gen-go-grpc, and protoc-gen-goswarm.
_PROTO_M = \
	Mgoogle/protobuf/timestamp.proto=google.golang.org/protobuf/types/known/timestamppb \
	Mgoogle/protobuf/duration.proto=google.golang.org/protobuf/types/known/durationpb \
	Mgoogle/protobuf/any.proto=google.golang.org/protobuf/types/known/anypb \
	Mgoogle/protobuf/wrappers.proto=google.golang.org/protobuf/types/known/wrapperspb \
	Mgoogle/protobuf/field_mask.proto=google.golang.org/protobuf/types/known/fieldmaskpb \
	Mprotobuf/plugin/plugin.proto=github.com/moby/swarmkit/v2/protobuf/plugin \
	Mapi/types.proto=github.com/moby/swarmkit/v2/api \
	Mapi/specs.proto=github.com/moby/swarmkit/v2/api \
	Mapi/objects.proto=github.com/moby/swarmkit/v2/api \
	Mapi/control.proto=github.com/moby/swarmkit/v2/api \
	Mapi/dispatcher.proto=github.com/moby/swarmkit/v2/api \
	Mapi/ca.proto=github.com/moby/swarmkit/v2/api \
	Mapi/watch.proto=github.com/moby/swarmkit/v2/api \
	Mapi/health.proto=github.com/moby/swarmkit/v2/api \
	Mapi/raft.proto=github.com/moby/swarmkit/v2/api \
	Mapi/resource.proto=github.com/moby/swarmkit/v2/api \
	Mapi/snapshot.proto=github.com/moby/swarmkit/v2/api \
	Mapi/logbroker.proto=github.com/moby/swarmkit/v2/api \
	Mgo.etcd.io/raft/v3/raftpb/raft.proto=go.etcd.io/raft/v3/raftpb

PROTO_M_FLAGS = $(addprefix --go_opt=,$(_PROTO_M)) \
	$(addprefix --go-grpc_opt=,$(_PROTO_M)) --go-grpc_opt=require_unimplemented_servers=false \
	$(addprefix --goswarm_opt=,$(_PROTO_M))

.PHONY: protos
protos: bin/protoc-gen-goswarm bin/proto-name-fix ## generate protobuf
	@echo "🐳 $@"
	@GOPATH_BIN=$$(go env GOPATH)/bin && PATH=${ROOTDIR}/bin:$${GOPATH_BIN}:${PATH} && \
		protoc $(PROTO_INCLUDES) \
		$(addprefix --go_opt=,$(_PROTO_M)) \
		--go_out=. --go_opt=paths=source_relative \
		protobuf/plugin/plugin.proto && \
		protoc $(PROTO_INCLUDES) $(PROTO_M_FLAGS) \
		--go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative \
		--goswarm_out=. --goswarm_opt=paths=source_relative \
		--plugin=protoc-gen-goswarm=${ROOTDIR}/bin/protoc-gen-goswarm \
		$(PROTO_SRCS)
	@echo "🐳 Applying name fixes..."
	@${ROOTDIR}/bin/proto-name-fix -rename-map=rename_map.json api/*.pb.go

.PHONY: checkprotos
checkprotos: protos ## check if protobufs needs to be generated again
	@echo "🐳 $@"
	@test -z "$$(git status --short | grep ".pb.go" | tee /dev/stderr)" || \
		((git diff | cat) && \
		(echo "👹 please run 'make protos' when making changes to proto files" && false))

.PHONY: check
check: fmt-proto
check: ## Run various source code validation tools
	@echo "🐳 $@"
	@./bin/golangci-lint run

.PHONY: fmt-proto
fmt-proto:
	@test -z "$$(find . -path ./vendor -prune -o ! -name timestamp.proto ! -name duration.proto -name '*.proto' -type f -exec grep -Hn -e "^ " {} \; | tee /dev/stderr)" || \
		(echo "👹 please indent proto files with tabs only" && false)

.PHONY: build
build: ## build the go packages
	@echo "🐳 $@"
	@go build -tags "${DOCKER_BUILDTAGS}" -v ${GO_LDFLAGS} ${GO_GCFLAGS} ${PACKAGES}

.PHONY: test
test: ## run tests, except integration tests
	@echo "🐳 $@"
	@go test -parallel 8 ${GO_TESTFLAGS} -tags "${DOCKER_BUILDTAGS}" $(filter-out ${INTEGRATION_PACKAGE},${PACKAGES})

.PHONY: integration-tests
integration-tests: ## run integration tests
	@echo "🐳 $@"
	@go test -parallel 8 ${GO_TESTFLAGS} -tags "${DOCKER_BUILDTAGS}" ${INTEGRATION_PACKAGE}

.PHONY: swarmd-tests
swarmd-tests: ## run swarmd tests
	@echo "🐳 $@"
	@cd swarmd && go test -parallel 8 ${GO_TESTFLAGS} -tags "${DOCKER_BUILDTAGS}" ./...

# Build a binary from a cmd.
bin/%: cmd/% .FORCE
	@echo "🐳 $@"
	@go build -tags "${DOCKER_BUILDTAGS}" -o $@ ${GO_LDFLAGS}  ${GO_GCFLAGS} ./$<

swarmd/bin/%: swarmd/cmd/% .FORCE
	@echo "🐳 $@"
	@cd swarmd && go build -tags "${DOCKER_BUILDTAGS}" -o ../$@ ${GO_LDFLAGS}  ${GO_GCFLAGS} ../$<

.PHONY: .FORCE
.FORCE:

.PHONY: binaries
binaries: $(BINARIES) $(SWARMD_BINARIES) ## build binaries
	@echo "🐳 $@"

.PHONY: clean
clean: ## clean up binaries
	@echo "🐳 $@"
	@rm -f $(BINARIES) $(SWARMD_BINARIES)

.PHONY: install
install: $(BINARIES) $(SWARMD_BINARIES) ## install binaries
	@echo "🐳 $@"
	@mkdir -p $(DESTDIR)/bin
	@install $(BINARIES) $(SWARMD_BINARIES) $(DESTDIR)/bin

.PHONY: uninstall
uninstall:
	@echo "🐳 $@"
	@rm -f $(addprefix $(DESTDIR)/bin/,$(notdir $(BINARIES)))

.PHONY: coverage
coverage: ## generate coverprofiles from the unit tests
	@echo "🐳 $@"
	@( for pkg in $(filter-out ${INTEGRATION_PACKAGE},${PACKAGES}); do \
		go test ${GO_TESTFLAGS} -tags "${DOCKER_BUILDTAGS}" -test.short -coverprofile="$$(go list -f "{{.Dir}}" $$pkg)/coverage.txt" -covermode=atomic $$pkg || exit; \
	done )

.PHONY: coverage-integration
coverage-integration: ## generate coverprofiles from the integration tests
	@echo "🐳 $@"
	go test ${GO_TESTFLAGS} -tags "${DOCKER_BUILDTAGS}" -test.short -coverprofile="$$(go list -f "{{.Dir}}" ${INTEGRATION_PACKAGE})/coverage.txt" -covermode=atomic ${INTEGRATION_PACKAGE}

.PHONY: help
help: ## this help
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

.PHONY: dep-validate
dep-validate: go-mod-vendor
	@echo "+ $@"
	@go mod tidy
	@git diff --exit-code go.mod go.sum vendor || \
		(echo >&2 "+ inconsistent dependencies! what you have in go.mod does not match with what you have in vendor" && false)

.PHONY: go-mod-vendor
go-mod-vendor:
	@go mod tidy
	@go mod vendor
