// Code generated by protoc-gen-goswarm. DO NOT EDIT.

package test

import (
	context "context"
)

type authenticatedWrapperRouteGuideServer struct {
	local     RouteGuideServer
	authorize func(context.Context, []string) error
}

func NewAuthenticatedWrapperRouteGuideServer(local RouteGuideServer, authorize func(context.Context, []string) error) RouteGuideServer {
	return &authenticatedWrapperRouteGuideServer{
		local:     local,
		authorize: authorize,
	}
}

func (p *authenticatedWrapperRouteGuideServer) GetFeature(ctx context.Context, r *Point) (*Feature, error) {

	panic("no authorization information in protobuf")
}

func (p *authenticatedWrapperRouteGuideServer) ListFeatures(r *Rectangle, stream RouteGuide_ListFeaturesServer) error {

	panic("no authorization information in protobuf")
}

func (p *authenticatedWrapperRouteGuideServer) RecordRoute(stream RouteGuide_RecordRouteServer) error {

	panic("no authorization information in protobuf")
}

func (p *authenticatedWrapperRouteGuideServer) RouteChat(stream RouteGuide_RouteChatServer) error {

	panic("no authorization information in protobuf")
}

type authenticatedWrapperHealthServer struct {
	local     HealthServer
	authorize func(context.Context, []string) error
}

func NewAuthenticatedWrapperHealthServer(local HealthServer, authorize func(context.Context, []string) error) HealthServer {
	return &authenticatedWrapperHealthServer{
		local:     local,
		authorize: authorize,
	}
}

func (p *authenticatedWrapperHealthServer) Check(ctx context.Context, r *HealthCheckRequest) (*HealthCheckResponse, error) {

	panic("no authorization information in protobuf")
}
