// Code generated by protoc-gen-goswarm. DO NOT EDIT.

package api

import (
	deepcopy "github.com/moby/swarmkit/v2/api/deepcopy"
	anypb "google.golang.org/protobuf/types/known/anypb"
)

func (m *GetNodeRequest) Copy() *GetNodeRequest {
	if m == nil {
		return nil
	}
	o := &GetNodeRequest{}
	o.CopyFrom(m)
	return o
}

func (m *GetNodeRequest) CopyFrom(src interface{}) {

	o := src.(*GetNodeRequest)
	m.NodeID = o.NodeID
}

func (m *GetNodeResponse) Copy() *GetNodeResponse {
	if m == nil {
		return nil
	}
	o := &GetNodeResponse{}
	o.CopyFrom(m)
	return o
}

func (m *GetNodeResponse) CopyFrom(src interface{}) {

	o := src.(*GetNodeResponse)
	if o.Node != nil {
		m.Node = &Node{}
		deepcopy.Copy(m.Node, o.Node)
	}

}

func (m *ListNodesRequest) Copy() *ListNodesRequest {
	if m == nil {
		return nil
	}
	o := &ListNodesRequest{}
	o.CopyFrom(m)
	return o
}

func (m *ListNodesRequest) CopyFrom(src interface{}) {

	o := src.(*ListNodesRequest)
	if o.Filters != nil {
		m.Filters = &ListNodesRequest_Filters{}
		deepcopy.Copy(m.Filters, o.Filters)
	}

}

func (m *ListNodesRequest_Filters) Copy() *ListNodesRequest_Filters {
	if m == nil {
		return nil
	}
	o := &ListNodesRequest_Filters{}
	o.CopyFrom(m)
	return o
}

func (m *ListNodesRequest_Filters) CopyFrom(src interface{}) {

	o := src.(*ListNodesRequest_Filters)
	if o.Names != nil {
		m.Names = make([]string, len(o.Names))
		copy(m.Names, o.Names)
	}

	if o.IDPrefixes != nil {
		m.IDPrefixes = make([]string, len(o.IDPrefixes))
		copy(m.IDPrefixes, o.IDPrefixes)
	}

	if o.Labels != nil {
		m.Labels = make(map[string]string, len(o.Labels))
		for k, v := range o.Labels {
			m.Labels[k] = v
		}
	}

	if o.NodeLabels != nil {
		m.NodeLabels = make(map[string]string, len(o.NodeLabels))
		for k, v := range o.NodeLabels {
			m.NodeLabels[k] = v
		}
	}

	if o.Memberships != nil {
		m.Memberships = make([]NodeSpec_Membership, len(o.Memberships))
		copy(m.Memberships, o.Memberships)
	}

	if o.Roles != nil {
		m.Roles = make([]NodeRole, len(o.Roles))
		copy(m.Roles, o.Roles)
	}

	if o.NamePrefixes != nil {
		m.NamePrefixes = make([]string, len(o.NamePrefixes))
		copy(m.NamePrefixes, o.NamePrefixes)
	}

}

func (m *ListNodesResponse) Copy() *ListNodesResponse {
	if m == nil {
		return nil
	}
	o := &ListNodesResponse{}
	o.CopyFrom(m)
	return o
}

func (m *ListNodesResponse) CopyFrom(src interface{}) {

	o := src.(*ListNodesResponse)
	if o.Nodes != nil {
		m.Nodes = make([]*Node, len(o.Nodes))
		for i := range m.Nodes {
			m.Nodes[i] = &Node{}
			deepcopy.Copy(m.Nodes[i], o.Nodes[i])
		}
	}

}

func (m *UpdateNodeRequest) Copy() *UpdateNodeRequest {
	if m == nil {
		return nil
	}
	o := &UpdateNodeRequest{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateNodeRequest) CopyFrom(src interface{}) {

	o := src.(*UpdateNodeRequest)
	m.NodeID = o.NodeID
	if o.NodeVersion != nil {
		m.NodeVersion = &Version{}
		deepcopy.Copy(m.NodeVersion, o.NodeVersion)
	}

	if o.Spec != nil {
		m.Spec = &NodeSpec{}
		deepcopy.Copy(m.Spec, o.Spec)
	}

}

func (m *UpdateNodeResponse) Copy() *UpdateNodeResponse {
	if m == nil {
		return nil
	}
	o := &UpdateNodeResponse{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateNodeResponse) CopyFrom(src interface{}) {

	o := src.(*UpdateNodeResponse)
	if o.Node != nil {
		m.Node = &Node{}
		deepcopy.Copy(m.Node, o.Node)
	}

}

func (m *RemoveNodeRequest) Copy() *RemoveNodeRequest {
	if m == nil {
		return nil
	}
	o := &RemoveNodeRequest{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveNodeRequest) CopyFrom(src interface{}) {

	o := src.(*RemoveNodeRequest)
	m.NodeID = o.NodeID
	m.Force = o.Force
}

func (m *RemoveNodeResponse) Copy() *RemoveNodeResponse {
	if m == nil {
		return nil
	}
	o := &RemoveNodeResponse{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveNodeResponse) CopyFrom(src interface{}) {}

func (m *GetTaskRequest) Copy() *GetTaskRequest {
	if m == nil {
		return nil
	}
	o := &GetTaskRequest{}
	o.CopyFrom(m)
	return o
}

func (m *GetTaskRequest) CopyFrom(src interface{}) {

	o := src.(*GetTaskRequest)
	m.TaskID = o.TaskID
}

func (m *GetTaskResponse) Copy() *GetTaskResponse {
	if m == nil {
		return nil
	}
	o := &GetTaskResponse{}
	o.CopyFrom(m)
	return o
}

func (m *GetTaskResponse) CopyFrom(src interface{}) {

	o := src.(*GetTaskResponse)
	if o.Task != nil {
		m.Task = &Task{}
		deepcopy.Copy(m.Task, o.Task)
	}

}

func (m *RemoveTaskRequest) Copy() *RemoveTaskRequest {
	if m == nil {
		return nil
	}
	o := &RemoveTaskRequest{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveTaskRequest) CopyFrom(src interface{}) {

	o := src.(*RemoveTaskRequest)
	m.TaskID = o.TaskID
}

func (m *RemoveTaskResponse) Copy() *RemoveTaskResponse {
	if m == nil {
		return nil
	}
	o := &RemoveTaskResponse{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveTaskResponse) CopyFrom(src interface{}) {}

func (m *ListTasksRequest) Copy() *ListTasksRequest {
	if m == nil {
		return nil
	}
	o := &ListTasksRequest{}
	o.CopyFrom(m)
	return o
}

func (m *ListTasksRequest) CopyFrom(src interface{}) {

	o := src.(*ListTasksRequest)
	if o.Filters != nil {
		m.Filters = &ListTasksRequest_Filters{}
		deepcopy.Copy(m.Filters, o.Filters)
	}

}

func (m *ListTasksRequest_Filters) Copy() *ListTasksRequest_Filters {
	if m == nil {
		return nil
	}
	o := &ListTasksRequest_Filters{}
	o.CopyFrom(m)
	return o
}

func (m *ListTasksRequest_Filters) CopyFrom(src interface{}) {

	o := src.(*ListTasksRequest_Filters)
	if o.Names != nil {
		m.Names = make([]string, len(o.Names))
		copy(m.Names, o.Names)
	}

	if o.IDPrefixes != nil {
		m.IDPrefixes = make([]string, len(o.IDPrefixes))
		copy(m.IDPrefixes, o.IDPrefixes)
	}

	if o.Labels != nil {
		m.Labels = make(map[string]string, len(o.Labels))
		for k, v := range o.Labels {
			m.Labels[k] = v
		}
	}

	if o.ServiceIDs != nil {
		m.ServiceIDs = make([]string, len(o.ServiceIDs))
		copy(m.ServiceIDs, o.ServiceIDs)
	}

	if o.NodeIDs != nil {
		m.NodeIDs = make([]string, len(o.NodeIDs))
		copy(m.NodeIDs, o.NodeIDs)
	}

	if o.DesiredStates != nil {
		m.DesiredStates = make([]TaskState, len(o.DesiredStates))
		copy(m.DesiredStates, o.DesiredStates)
	}

	if o.NamePrefixes != nil {
		m.NamePrefixes = make([]string, len(o.NamePrefixes))
		copy(m.NamePrefixes, o.NamePrefixes)
	}

	if o.Runtimes != nil {
		m.Runtimes = make([]string, len(o.Runtimes))
		copy(m.Runtimes, o.Runtimes)
	}

	m.UpToDate = o.UpToDate
}

func (m *ListTasksResponse) Copy() *ListTasksResponse {
	if m == nil {
		return nil
	}
	o := &ListTasksResponse{}
	o.CopyFrom(m)
	return o
}

func (m *ListTasksResponse) CopyFrom(src interface{}) {

	o := src.(*ListTasksResponse)
	if o.Tasks != nil {
		m.Tasks = make([]*Task, len(o.Tasks))
		for i := range m.Tasks {
			m.Tasks[i] = &Task{}
			deepcopy.Copy(m.Tasks[i], o.Tasks[i])
		}
	}

}

func (m *CreateServiceRequest) Copy() *CreateServiceRequest {
	if m == nil {
		return nil
	}
	o := &CreateServiceRequest{}
	o.CopyFrom(m)
	return o
}

func (m *CreateServiceRequest) CopyFrom(src interface{}) {

	o := src.(*CreateServiceRequest)
	if o.Spec != nil {
		m.Spec = &ServiceSpec{}
		deepcopy.Copy(m.Spec, o.Spec)
	}

}

func (m *CreateServiceResponse) Copy() *CreateServiceResponse {
	if m == nil {
		return nil
	}
	o := &CreateServiceResponse{}
	o.CopyFrom(m)
	return o
}

func (m *CreateServiceResponse) CopyFrom(src interface{}) {

	o := src.(*CreateServiceResponse)
	if o.Service != nil {
		m.Service = &Service{}
		deepcopy.Copy(m.Service, o.Service)
	}

}

func (m *GetServiceRequest) Copy() *GetServiceRequest {
	if m == nil {
		return nil
	}
	o := &GetServiceRequest{}
	o.CopyFrom(m)
	return o
}

func (m *GetServiceRequest) CopyFrom(src interface{}) {

	o := src.(*GetServiceRequest)
	m.ServiceID = o.ServiceID
	m.InsertDefaults = o.InsertDefaults
}

func (m *GetServiceResponse) Copy() *GetServiceResponse {
	if m == nil {
		return nil
	}
	o := &GetServiceResponse{}
	o.CopyFrom(m)
	return o
}

func (m *GetServiceResponse) CopyFrom(src interface{}) {

	o := src.(*GetServiceResponse)
	if o.Service != nil {
		m.Service = &Service{}
		deepcopy.Copy(m.Service, o.Service)
	}

}

func (m *UpdateServiceRequest) Copy() *UpdateServiceRequest {
	if m == nil {
		return nil
	}
	o := &UpdateServiceRequest{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateServiceRequest) CopyFrom(src interface{}) {

	o := src.(*UpdateServiceRequest)
	m.ServiceID = o.ServiceID
	if o.ServiceVersion != nil {
		m.ServiceVersion = &Version{}
		deepcopy.Copy(m.ServiceVersion, o.ServiceVersion)
	}

	if o.Spec != nil {
		m.Spec = &ServiceSpec{}
		deepcopy.Copy(m.Spec, o.Spec)
	}

	m.Rollback = o.Rollback
}

func (m *UpdateServiceResponse) Copy() *UpdateServiceResponse {
	if m == nil {
		return nil
	}
	o := &UpdateServiceResponse{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateServiceResponse) CopyFrom(src interface{}) {

	o := src.(*UpdateServiceResponse)
	if o.Service != nil {
		m.Service = &Service{}
		deepcopy.Copy(m.Service, o.Service)
	}

}

func (m *RemoveServiceRequest) Copy() *RemoveServiceRequest {
	if m == nil {
		return nil
	}
	o := &RemoveServiceRequest{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveServiceRequest) CopyFrom(src interface{}) {

	o := src.(*RemoveServiceRequest)
	m.ServiceID = o.ServiceID
}

func (m *RemoveServiceResponse) Copy() *RemoveServiceResponse {
	if m == nil {
		return nil
	}
	o := &RemoveServiceResponse{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveServiceResponse) CopyFrom(src interface{}) {}

func (m *ListServicesRequest) Copy() *ListServicesRequest {
	if m == nil {
		return nil
	}
	o := &ListServicesRequest{}
	o.CopyFrom(m)
	return o
}

func (m *ListServicesRequest) CopyFrom(src interface{}) {

	o := src.(*ListServicesRequest)
	if o.Filters != nil {
		m.Filters = &ListServicesRequest_Filters{}
		deepcopy.Copy(m.Filters, o.Filters)
	}

}

func (m *ListServicesRequest_Filters) Copy() *ListServicesRequest_Filters {
	if m == nil {
		return nil
	}
	o := &ListServicesRequest_Filters{}
	o.CopyFrom(m)
	return o
}

func (m *ListServicesRequest_Filters) CopyFrom(src interface{}) {

	o := src.(*ListServicesRequest_Filters)
	if o.Names != nil {
		m.Names = make([]string, len(o.Names))
		copy(m.Names, o.Names)
	}

	if o.IDPrefixes != nil {
		m.IDPrefixes = make([]string, len(o.IDPrefixes))
		copy(m.IDPrefixes, o.IDPrefixes)
	}

	if o.Labels != nil {
		m.Labels = make(map[string]string, len(o.Labels))
		for k, v := range o.Labels {
			m.Labels[k] = v
		}
	}

	if o.NamePrefixes != nil {
		m.NamePrefixes = make([]string, len(o.NamePrefixes))
		copy(m.NamePrefixes, o.NamePrefixes)
	}

	if o.Runtimes != nil {
		m.Runtimes = make([]string, len(o.Runtimes))
		copy(m.Runtimes, o.Runtimes)
	}

}

func (m *ListServicesResponse) Copy() *ListServicesResponse {
	if m == nil {
		return nil
	}
	o := &ListServicesResponse{}
	o.CopyFrom(m)
	return o
}

func (m *ListServicesResponse) CopyFrom(src interface{}) {

	o := src.(*ListServicesResponse)
	if o.Services != nil {
		m.Services = make([]*Service, len(o.Services))
		for i := range m.Services {
			m.Services[i] = &Service{}
			deepcopy.Copy(m.Services[i], o.Services[i])
		}
	}

}

func (m *ListServiceStatusesRequest) Copy() *ListServiceStatusesRequest {
	if m == nil {
		return nil
	}
	o := &ListServiceStatusesRequest{}
	o.CopyFrom(m)
	return o
}

func (m *ListServiceStatusesRequest) CopyFrom(src interface{}) {

	o := src.(*ListServiceStatusesRequest)
	if o.Services != nil {
		m.Services = make([]string, len(o.Services))
		copy(m.Services, o.Services)
	}

}

func (m *ListServiceStatusesResponse) Copy() *ListServiceStatusesResponse {
	if m == nil {
		return nil
	}
	o := &ListServiceStatusesResponse{}
	o.CopyFrom(m)
	return o
}

func (m *ListServiceStatusesResponse) CopyFrom(src interface{}) {

	o := src.(*ListServiceStatusesResponse)
	if o.Statuses != nil {
		m.Statuses = make([]*ListServiceStatusesResponse_ServiceStatus, len(o.Statuses))
		for i := range m.Statuses {
			m.Statuses[i] = &ListServiceStatusesResponse_ServiceStatus{}
			deepcopy.Copy(m.Statuses[i], o.Statuses[i])
		}
	}

}

func (m *ListServiceStatusesResponse_ServiceStatus) Copy() *ListServiceStatusesResponse_ServiceStatus {
	if m == nil {
		return nil
	}
	o := &ListServiceStatusesResponse_ServiceStatus{}
	o.CopyFrom(m)
	return o
}

func (m *ListServiceStatusesResponse_ServiceStatus) CopyFrom(src interface{}) {

	o := src.(*ListServiceStatusesResponse_ServiceStatus)
	m.ServiceID = o.ServiceID
	m.DesiredTasks = o.DesiredTasks
	m.RunningTasks = o.RunningTasks
	m.CompletedTasks = o.CompletedTasks
}

func (m *CreateNetworkRequest) Copy() *CreateNetworkRequest {
	if m == nil {
		return nil
	}
	o := &CreateNetworkRequest{}
	o.CopyFrom(m)
	return o
}

func (m *CreateNetworkRequest) CopyFrom(src interface{}) {

	o := src.(*CreateNetworkRequest)
	if o.Spec != nil {
		m.Spec = &NetworkSpec{}
		deepcopy.Copy(m.Spec, o.Spec)
	}

}

func (m *CreateNetworkResponse) Copy() *CreateNetworkResponse {
	if m == nil {
		return nil
	}
	o := &CreateNetworkResponse{}
	o.CopyFrom(m)
	return o
}

func (m *CreateNetworkResponse) CopyFrom(src interface{}) {

	o := src.(*CreateNetworkResponse)
	if o.Network != nil {
		m.Network = &Network{}
		deepcopy.Copy(m.Network, o.Network)
	}

}

func (m *GetNetworkRequest) Copy() *GetNetworkRequest {
	if m == nil {
		return nil
	}
	o := &GetNetworkRequest{}
	o.CopyFrom(m)
	return o
}

func (m *GetNetworkRequest) CopyFrom(src interface{}) {

	o := src.(*GetNetworkRequest)
	m.Name = o.Name
	m.NetworkID = o.NetworkID
	if o.Appdata != nil {
		m.Appdata = &anypb.Any{}
		deepcopy.Copy(m.Appdata, o.Appdata)
	}

}

func (m *GetNetworkResponse) Copy() *GetNetworkResponse {
	if m == nil {
		return nil
	}
	o := &GetNetworkResponse{}
	o.CopyFrom(m)
	return o
}

func (m *GetNetworkResponse) CopyFrom(src interface{}) {

	o := src.(*GetNetworkResponse)
	if o.Network != nil {
		m.Network = &Network{}
		deepcopy.Copy(m.Network, o.Network)
	}

}

func (m *RemoveNetworkRequest) Copy() *RemoveNetworkRequest {
	if m == nil {
		return nil
	}
	o := &RemoveNetworkRequest{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveNetworkRequest) CopyFrom(src interface{}) {

	o := src.(*RemoveNetworkRequest)
	m.Name = o.Name
	m.NetworkID = o.NetworkID
}

func (m *RemoveNetworkResponse) Copy() *RemoveNetworkResponse {
	if m == nil {
		return nil
	}
	o := &RemoveNetworkResponse{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveNetworkResponse) CopyFrom(src interface{}) {}

func (m *ListNetworksRequest) Copy() *ListNetworksRequest {
	if m == nil {
		return nil
	}
	o := &ListNetworksRequest{}
	o.CopyFrom(m)
	return o
}

func (m *ListNetworksRequest) CopyFrom(src interface{}) {

	o := src.(*ListNetworksRequest)
	if o.Filters != nil {
		m.Filters = &ListNetworksRequest_Filters{}
		deepcopy.Copy(m.Filters, o.Filters)
	}

	if o.Appdata != nil {
		m.Appdata = &anypb.Any{}
		deepcopy.Copy(m.Appdata, o.Appdata)
	}

}

func (m *ListNetworksRequest_Filters) Copy() *ListNetworksRequest_Filters {
	if m == nil {
		return nil
	}
	o := &ListNetworksRequest_Filters{}
	o.CopyFrom(m)
	return o
}

func (m *ListNetworksRequest_Filters) CopyFrom(src interface{}) {

	o := src.(*ListNetworksRequest_Filters)
	if o.Names != nil {
		m.Names = make([]string, len(o.Names))
		copy(m.Names, o.Names)
	}

	if o.IDPrefixes != nil {
		m.IDPrefixes = make([]string, len(o.IDPrefixes))
		copy(m.IDPrefixes, o.IDPrefixes)
	}

	if o.Labels != nil {
		m.Labels = make(map[string]string, len(o.Labels))
		for k, v := range o.Labels {
			m.Labels[k] = v
		}
	}

	if o.NamePrefixes != nil {
		m.NamePrefixes = make([]string, len(o.NamePrefixes))
		copy(m.NamePrefixes, o.NamePrefixes)
	}

}

func (m *ListNetworksResponse) Copy() *ListNetworksResponse {
	if m == nil {
		return nil
	}
	o := &ListNetworksResponse{}
	o.CopyFrom(m)
	return o
}

func (m *ListNetworksResponse) CopyFrom(src interface{}) {

	o := src.(*ListNetworksResponse)
	if o.Networks != nil {
		m.Networks = make([]*Network, len(o.Networks))
		for i := range m.Networks {
			m.Networks[i] = &Network{}
			deepcopy.Copy(m.Networks[i], o.Networks[i])
		}
	}

}

func (m *GetClusterRequest) Copy() *GetClusterRequest {
	if m == nil {
		return nil
	}
	o := &GetClusterRequest{}
	o.CopyFrom(m)
	return o
}

func (m *GetClusterRequest) CopyFrom(src interface{}) {

	o := src.(*GetClusterRequest)
	m.ClusterID = o.ClusterID
}

func (m *GetClusterResponse) Copy() *GetClusterResponse {
	if m == nil {
		return nil
	}
	o := &GetClusterResponse{}
	o.CopyFrom(m)
	return o
}

func (m *GetClusterResponse) CopyFrom(src interface{}) {

	o := src.(*GetClusterResponse)
	if o.Cluster != nil {
		m.Cluster = &Cluster{}
		deepcopy.Copy(m.Cluster, o.Cluster)
	}

}

func (m *ListClustersRequest) Copy() *ListClustersRequest {
	if m == nil {
		return nil
	}
	o := &ListClustersRequest{}
	o.CopyFrom(m)
	return o
}

func (m *ListClustersRequest) CopyFrom(src interface{}) {

	o := src.(*ListClustersRequest)
	if o.Filters != nil {
		m.Filters = &ListClustersRequest_Filters{}
		deepcopy.Copy(m.Filters, o.Filters)
	}

}

func (m *ListClustersRequest_Filters) Copy() *ListClustersRequest_Filters {
	if m == nil {
		return nil
	}
	o := &ListClustersRequest_Filters{}
	o.CopyFrom(m)
	return o
}

func (m *ListClustersRequest_Filters) CopyFrom(src interface{}) {

	o := src.(*ListClustersRequest_Filters)
	if o.Names != nil {
		m.Names = make([]string, len(o.Names))
		copy(m.Names, o.Names)
	}

	if o.IDPrefixes != nil {
		m.IDPrefixes = make([]string, len(o.IDPrefixes))
		copy(m.IDPrefixes, o.IDPrefixes)
	}

	if o.Labels != nil {
		m.Labels = make(map[string]string, len(o.Labels))
		for k, v := range o.Labels {
			m.Labels[k] = v
		}
	}

	if o.NamePrefixes != nil {
		m.NamePrefixes = make([]string, len(o.NamePrefixes))
		copy(m.NamePrefixes, o.NamePrefixes)
	}

}

func (m *ListClustersResponse) Copy() *ListClustersResponse {
	if m == nil {
		return nil
	}
	o := &ListClustersResponse{}
	o.CopyFrom(m)
	return o
}

func (m *ListClustersResponse) CopyFrom(src interface{}) {

	o := src.(*ListClustersResponse)
	if o.Clusters != nil {
		m.Clusters = make([]*Cluster, len(o.Clusters))
		for i := range m.Clusters {
			m.Clusters[i] = &Cluster{}
			deepcopy.Copy(m.Clusters[i], o.Clusters[i])
		}
	}

}

func (m *KeyRotation) Copy() *KeyRotation {
	if m == nil {
		return nil
	}
	o := &KeyRotation{}
	o.CopyFrom(m)
	return o
}

func (m *KeyRotation) CopyFrom(src interface{}) {

	o := src.(*KeyRotation)
	m.WorkerJoinToken = o.WorkerJoinToken
	m.ManagerJoinToken = o.ManagerJoinToken
	m.ManagerUnlockKey = o.ManagerUnlockKey
}

func (m *UpdateClusterRequest) Copy() *UpdateClusterRequest {
	if m == nil {
		return nil
	}
	o := &UpdateClusterRequest{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateClusterRequest) CopyFrom(src interface{}) {

	o := src.(*UpdateClusterRequest)
	m.ClusterID = o.ClusterID
	if o.ClusterVersion != nil {
		m.ClusterVersion = &Version{}
		deepcopy.Copy(m.ClusterVersion, o.ClusterVersion)
	}

	if o.Spec != nil {
		m.Spec = &ClusterSpec{}
		deepcopy.Copy(m.Spec, o.Spec)
	}

	if o.Rotation != nil {
		m.Rotation = &KeyRotation{}
		deepcopy.Copy(m.Rotation, o.Rotation)
	}

}

func (m *UpdateClusterResponse) Copy() *UpdateClusterResponse {
	if m == nil {
		return nil
	}
	o := &UpdateClusterResponse{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateClusterResponse) CopyFrom(src interface{}) {

	o := src.(*UpdateClusterResponse)
	if o.Cluster != nil {
		m.Cluster = &Cluster{}
		deepcopy.Copy(m.Cluster, o.Cluster)
	}

}

func (m *GetSecretRequest) Copy() *GetSecretRequest {
	if m == nil {
		return nil
	}
	o := &GetSecretRequest{}
	o.CopyFrom(m)
	return o
}

func (m *GetSecretRequest) CopyFrom(src interface{}) {

	o := src.(*GetSecretRequest)
	m.SecretID = o.SecretID
}

func (m *GetSecretResponse) Copy() *GetSecretResponse {
	if m == nil {
		return nil
	}
	o := &GetSecretResponse{}
	o.CopyFrom(m)
	return o
}

func (m *GetSecretResponse) CopyFrom(src interface{}) {

	o := src.(*GetSecretResponse)
	if o.Secret != nil {
		m.Secret = &Secret{}
		deepcopy.Copy(m.Secret, o.Secret)
	}

}

func (m *UpdateSecretRequest) Copy() *UpdateSecretRequest {
	if m == nil {
		return nil
	}
	o := &UpdateSecretRequest{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateSecretRequest) CopyFrom(src interface{}) {

	o := src.(*UpdateSecretRequest)
	m.SecretID = o.SecretID
	if o.SecretVersion != nil {
		m.SecretVersion = &Version{}
		deepcopy.Copy(m.SecretVersion, o.SecretVersion)
	}

	if o.Spec != nil {
		m.Spec = &SecretSpec{}
		deepcopy.Copy(m.Spec, o.Spec)
	}

}

func (m *UpdateSecretResponse) Copy() *UpdateSecretResponse {
	if m == nil {
		return nil
	}
	o := &UpdateSecretResponse{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateSecretResponse) CopyFrom(src interface{}) {

	o := src.(*UpdateSecretResponse)
	if o.Secret != nil {
		m.Secret = &Secret{}
		deepcopy.Copy(m.Secret, o.Secret)
	}

}

func (m *ListSecretsRequest) Copy() *ListSecretsRequest {
	if m == nil {
		return nil
	}
	o := &ListSecretsRequest{}
	o.CopyFrom(m)
	return o
}

func (m *ListSecretsRequest) CopyFrom(src interface{}) {

	o := src.(*ListSecretsRequest)
	if o.Filters != nil {
		m.Filters = &ListSecretsRequest_Filters{}
		deepcopy.Copy(m.Filters, o.Filters)
	}

}

func (m *ListSecretsRequest_Filters) Copy() *ListSecretsRequest_Filters {
	if m == nil {
		return nil
	}
	o := &ListSecretsRequest_Filters{}
	o.CopyFrom(m)
	return o
}

func (m *ListSecretsRequest_Filters) CopyFrom(src interface{}) {

	o := src.(*ListSecretsRequest_Filters)
	if o.Names != nil {
		m.Names = make([]string, len(o.Names))
		copy(m.Names, o.Names)
	}

	if o.IDPrefixes != nil {
		m.IDPrefixes = make([]string, len(o.IDPrefixes))
		copy(m.IDPrefixes, o.IDPrefixes)
	}

	if o.Labels != nil {
		m.Labels = make(map[string]string, len(o.Labels))
		for k, v := range o.Labels {
			m.Labels[k] = v
		}
	}

	if o.NamePrefixes != nil {
		m.NamePrefixes = make([]string, len(o.NamePrefixes))
		copy(m.NamePrefixes, o.NamePrefixes)
	}

}

func (m *ListSecretsResponse) Copy() *ListSecretsResponse {
	if m == nil {
		return nil
	}
	o := &ListSecretsResponse{}
	o.CopyFrom(m)
	return o
}

func (m *ListSecretsResponse) CopyFrom(src interface{}) {

	o := src.(*ListSecretsResponse)
	if o.Secrets != nil {
		m.Secrets = make([]*Secret, len(o.Secrets))
		for i := range m.Secrets {
			m.Secrets[i] = &Secret{}
			deepcopy.Copy(m.Secrets[i], o.Secrets[i])
		}
	}

}

func (m *CreateSecretRequest) Copy() *CreateSecretRequest {
	if m == nil {
		return nil
	}
	o := &CreateSecretRequest{}
	o.CopyFrom(m)
	return o
}

func (m *CreateSecretRequest) CopyFrom(src interface{}) {

	o := src.(*CreateSecretRequest)
	if o.Spec != nil {
		m.Spec = &SecretSpec{}
		deepcopy.Copy(m.Spec, o.Spec)
	}

}

func (m *CreateSecretResponse) Copy() *CreateSecretResponse {
	if m == nil {
		return nil
	}
	o := &CreateSecretResponse{}
	o.CopyFrom(m)
	return o
}

func (m *CreateSecretResponse) CopyFrom(src interface{}) {

	o := src.(*CreateSecretResponse)
	if o.Secret != nil {
		m.Secret = &Secret{}
		deepcopy.Copy(m.Secret, o.Secret)
	}

}

func (m *RemoveSecretRequest) Copy() *RemoveSecretRequest {
	if m == nil {
		return nil
	}
	o := &RemoveSecretRequest{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveSecretRequest) CopyFrom(src interface{}) {

	o := src.(*RemoveSecretRequest)
	m.SecretID = o.SecretID
}

func (m *RemoveSecretResponse) Copy() *RemoveSecretResponse {
	if m == nil {
		return nil
	}
	o := &RemoveSecretResponse{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveSecretResponse) CopyFrom(src interface{}) {}

func (m *GetConfigRequest) Copy() *GetConfigRequest {
	if m == nil {
		return nil
	}
	o := &GetConfigRequest{}
	o.CopyFrom(m)
	return o
}

func (m *GetConfigRequest) CopyFrom(src interface{}) {

	o := src.(*GetConfigRequest)
	m.ConfigID = o.ConfigID
}

func (m *GetConfigResponse) Copy() *GetConfigResponse {
	if m == nil {
		return nil
	}
	o := &GetConfigResponse{}
	o.CopyFrom(m)
	return o
}

func (m *GetConfigResponse) CopyFrom(src interface{}) {

	o := src.(*GetConfigResponse)
	if o.Config != nil {
		m.Config = &Config{}
		deepcopy.Copy(m.Config, o.Config)
	}

}

func (m *UpdateConfigRequest) Copy() *UpdateConfigRequest {
	if m == nil {
		return nil
	}
	o := &UpdateConfigRequest{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateConfigRequest) CopyFrom(src interface{}) {

	o := src.(*UpdateConfigRequest)
	m.ConfigID = o.ConfigID
	if o.ConfigVersion != nil {
		m.ConfigVersion = &Version{}
		deepcopy.Copy(m.ConfigVersion, o.ConfigVersion)
	}

	if o.Spec != nil {
		m.Spec = &ConfigSpec{}
		deepcopy.Copy(m.Spec, o.Spec)
	}

}

func (m *UpdateConfigResponse) Copy() *UpdateConfigResponse {
	if m == nil {
		return nil
	}
	o := &UpdateConfigResponse{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateConfigResponse) CopyFrom(src interface{}) {

	o := src.(*UpdateConfigResponse)
	if o.Config != nil {
		m.Config = &Config{}
		deepcopy.Copy(m.Config, o.Config)
	}

}

func (m *ListConfigsRequest) Copy() *ListConfigsRequest {
	if m == nil {
		return nil
	}
	o := &ListConfigsRequest{}
	o.CopyFrom(m)
	return o
}

func (m *ListConfigsRequest) CopyFrom(src interface{}) {

	o := src.(*ListConfigsRequest)
	if o.Filters != nil {
		m.Filters = &ListConfigsRequest_Filters{}
		deepcopy.Copy(m.Filters, o.Filters)
	}

}

func (m *ListConfigsRequest_Filters) Copy() *ListConfigsRequest_Filters {
	if m == nil {
		return nil
	}
	o := &ListConfigsRequest_Filters{}
	o.CopyFrom(m)
	return o
}

func (m *ListConfigsRequest_Filters) CopyFrom(src interface{}) {

	o := src.(*ListConfigsRequest_Filters)
	if o.Names != nil {
		m.Names = make([]string, len(o.Names))
		copy(m.Names, o.Names)
	}

	if o.IDPrefixes != nil {
		m.IDPrefixes = make([]string, len(o.IDPrefixes))
		copy(m.IDPrefixes, o.IDPrefixes)
	}

	if o.Labels != nil {
		m.Labels = make(map[string]string, len(o.Labels))
		for k, v := range o.Labels {
			m.Labels[k] = v
		}
	}

	if o.NamePrefixes != nil {
		m.NamePrefixes = make([]string, len(o.NamePrefixes))
		copy(m.NamePrefixes, o.NamePrefixes)
	}

}

func (m *ListConfigsResponse) Copy() *ListConfigsResponse {
	if m == nil {
		return nil
	}
	o := &ListConfigsResponse{}
	o.CopyFrom(m)
	return o
}

func (m *ListConfigsResponse) CopyFrom(src interface{}) {

	o := src.(*ListConfigsResponse)
	if o.Configs != nil {
		m.Configs = make([]*Config, len(o.Configs))
		for i := range m.Configs {
			m.Configs[i] = &Config{}
			deepcopy.Copy(m.Configs[i], o.Configs[i])
		}
	}

}

func (m *CreateConfigRequest) Copy() *CreateConfigRequest {
	if m == nil {
		return nil
	}
	o := &CreateConfigRequest{}
	o.CopyFrom(m)
	return o
}

func (m *CreateConfigRequest) CopyFrom(src interface{}) {

	o := src.(*CreateConfigRequest)
	if o.Spec != nil {
		m.Spec = &ConfigSpec{}
		deepcopy.Copy(m.Spec, o.Spec)
	}

}

func (m *CreateConfigResponse) Copy() *CreateConfigResponse {
	if m == nil {
		return nil
	}
	o := &CreateConfigResponse{}
	o.CopyFrom(m)
	return o
}

func (m *CreateConfigResponse) CopyFrom(src interface{}) {

	o := src.(*CreateConfigResponse)
	if o.Config != nil {
		m.Config = &Config{}
		deepcopy.Copy(m.Config, o.Config)
	}

}

func (m *RemoveConfigRequest) Copy() *RemoveConfigRequest {
	if m == nil {
		return nil
	}
	o := &RemoveConfigRequest{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveConfigRequest) CopyFrom(src interface{}) {

	o := src.(*RemoveConfigRequest)
	m.ConfigID = o.ConfigID
}

func (m *RemoveConfigResponse) Copy() *RemoveConfigResponse {
	if m == nil {
		return nil
	}
	o := &RemoveConfigResponse{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveConfigResponse) CopyFrom(src interface{}) {}

func (m *CreateExtensionRequest) Copy() *CreateExtensionRequest {
	if m == nil {
		return nil
	}
	o := &CreateExtensionRequest{}
	o.CopyFrom(m)
	return o
}

func (m *CreateExtensionRequest) CopyFrom(src interface{}) {

	o := src.(*CreateExtensionRequest)
	if o.Annotations != nil {
		m.Annotations = &Annotations{}
		deepcopy.Copy(m.Annotations, o.Annotations)
	}

	m.Description = o.Description
}

func (m *CreateExtensionResponse) Copy() *CreateExtensionResponse {
	if m == nil {
		return nil
	}
	o := &CreateExtensionResponse{}
	o.CopyFrom(m)
	return o
}

func (m *CreateExtensionResponse) CopyFrom(src interface{}) {

	o := src.(*CreateExtensionResponse)
	if o.Extension != nil {
		m.Extension = &Extension{}
		deepcopy.Copy(m.Extension, o.Extension)
	}

}

func (m *RemoveExtensionRequest) Copy() *RemoveExtensionRequest {
	if m == nil {
		return nil
	}
	o := &RemoveExtensionRequest{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveExtensionRequest) CopyFrom(src interface{}) {

	o := src.(*RemoveExtensionRequest)
	m.ExtensionID = o.ExtensionID
}

func (m *RemoveExtensionResponse) Copy() *RemoveExtensionResponse {
	if m == nil {
		return nil
	}
	o := &RemoveExtensionResponse{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveExtensionResponse) CopyFrom(src interface{}) {}

func (m *GetExtensionRequest) Copy() *GetExtensionRequest {
	if m == nil {
		return nil
	}
	o := &GetExtensionRequest{}
	o.CopyFrom(m)
	return o
}

func (m *GetExtensionRequest) CopyFrom(src interface{}) {

	o := src.(*GetExtensionRequest)
	m.ExtensionID = o.ExtensionID
}

func (m *GetExtensionResponse) Copy() *GetExtensionResponse {
	if m == nil {
		return nil
	}
	o := &GetExtensionResponse{}
	o.CopyFrom(m)
	return o
}

func (m *GetExtensionResponse) CopyFrom(src interface{}) {

	o := src.(*GetExtensionResponse)
	if o.Extension != nil {
		m.Extension = &Extension{}
		deepcopy.Copy(m.Extension, o.Extension)
	}

}

func (m *CreateResourceRequest) Copy() *CreateResourceRequest {
	if m == nil {
		return nil
	}
	o := &CreateResourceRequest{}
	o.CopyFrom(m)
	return o
}

func (m *CreateResourceRequest) CopyFrom(src interface{}) {

	o := src.(*CreateResourceRequest)
	if o.Annotations != nil {
		m.Annotations = &Annotations{}
		deepcopy.Copy(m.Annotations, o.Annotations)
	}

	m.Kind = o.Kind
	if o.Payload != nil {
		m.Payload = &anypb.Any{}
		deepcopy.Copy(m.Payload, o.Payload)
	}

}

func (m *CreateResourceResponse) Copy() *CreateResourceResponse {
	if m == nil {
		return nil
	}
	o := &CreateResourceResponse{}
	o.CopyFrom(m)
	return o
}

func (m *CreateResourceResponse) CopyFrom(src interface{}) {

	o := src.(*CreateResourceResponse)
	if o.Resource != nil {
		m.Resource = &Resource{}
		deepcopy.Copy(m.Resource, o.Resource)
	}

}

func (m *RemoveResourceRequest) Copy() *RemoveResourceRequest {
	if m == nil {
		return nil
	}
	o := &RemoveResourceRequest{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveResourceRequest) CopyFrom(src interface{}) {

	o := src.(*RemoveResourceRequest)
	m.ResourceID = o.ResourceID
}

func (m *RemoveResourceResponse) Copy() *RemoveResourceResponse {
	if m == nil {
		return nil
	}
	o := &RemoveResourceResponse{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveResourceResponse) CopyFrom(src interface{}) {}

func (m *UpdateResourceRequest) Copy() *UpdateResourceRequest {
	if m == nil {
		return nil
	}
	o := &UpdateResourceRequest{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateResourceRequest) CopyFrom(src interface{}) {

	o := src.(*UpdateResourceRequest)
	m.ResourceID = o.ResourceID
	if o.ResourceVersion != nil {
		m.ResourceVersion = &Version{}
		deepcopy.Copy(m.ResourceVersion, o.ResourceVersion)
	}

	if o.Annotations != nil {
		m.Annotations = &Annotations{}
		deepcopy.Copy(m.Annotations, o.Annotations)
	}

	if o.Payload != nil {
		m.Payload = &anypb.Any{}
		deepcopy.Copy(m.Payload, o.Payload)
	}

}

func (m *UpdateResourceResponse) Copy() *UpdateResourceResponse {
	if m == nil {
		return nil
	}
	o := &UpdateResourceResponse{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateResourceResponse) CopyFrom(src interface{}) {

	o := src.(*UpdateResourceResponse)
	if o.Resource != nil {
		m.Resource = &Resource{}
		deepcopy.Copy(m.Resource, o.Resource)
	}

}

func (m *GetResourceRequest) Copy() *GetResourceRequest {
	if m == nil {
		return nil
	}
	o := &GetResourceRequest{}
	o.CopyFrom(m)
	return o
}

func (m *GetResourceRequest) CopyFrom(src interface{}) {

	o := src.(*GetResourceRequest)
	m.ResourceID = o.ResourceID
}

func (m *GetResourceResponse) Copy() *GetResourceResponse {
	if m == nil {
		return nil
	}
	o := &GetResourceResponse{}
	o.CopyFrom(m)
	return o
}

func (m *GetResourceResponse) CopyFrom(src interface{}) {

	o := src.(*GetResourceResponse)
	if o.Resource != nil {
		m.Resource = &Resource{}
		deepcopy.Copy(m.Resource, o.Resource)
	}

}

func (m *ListResourcesRequest) Copy() *ListResourcesRequest {
	if m == nil {
		return nil
	}
	o := &ListResourcesRequest{}
	o.CopyFrom(m)
	return o
}

func (m *ListResourcesRequest) CopyFrom(src interface{}) {

	o := src.(*ListResourcesRequest)
	if o.Filters != nil {
		m.Filters = &ListResourcesRequest_Filters{}
		deepcopy.Copy(m.Filters, o.Filters)
	}

}

func (m *ListResourcesRequest_Filters) Copy() *ListResourcesRequest_Filters {
	if m == nil {
		return nil
	}
	o := &ListResourcesRequest_Filters{}
	o.CopyFrom(m)
	return o
}

func (m *ListResourcesRequest_Filters) CopyFrom(src interface{}) {

	o := src.(*ListResourcesRequest_Filters)
	if o.Names != nil {
		m.Names = make([]string, len(o.Names))
		copy(m.Names, o.Names)
	}

	if o.IDPrefixes != nil {
		m.IDPrefixes = make([]string, len(o.IDPrefixes))
		copy(m.IDPrefixes, o.IDPrefixes)
	}

	if o.Labels != nil {
		m.Labels = make(map[string]string, len(o.Labels))
		for k, v := range o.Labels {
			m.Labels[k] = v
		}
	}

	if o.NamePrefixes != nil {
		m.NamePrefixes = make([]string, len(o.NamePrefixes))
		copy(m.NamePrefixes, o.NamePrefixes)
	}

	m.Kind = o.Kind
}

func (m *ListResourcesResponse) Copy() *ListResourcesResponse {
	if m == nil {
		return nil
	}
	o := &ListResourcesResponse{}
	o.CopyFrom(m)
	return o
}

func (m *ListResourcesResponse) CopyFrom(src interface{}) {

	o := src.(*ListResourcesResponse)
	if o.Resources != nil {
		m.Resources = make([]*Resource, len(o.Resources))
		for i := range m.Resources {
			m.Resources[i] = &Resource{}
			deepcopy.Copy(m.Resources[i], o.Resources[i])
		}
	}

}

func (m *CreateVolumeRequest) Copy() *CreateVolumeRequest {
	if m == nil {
		return nil
	}
	o := &CreateVolumeRequest{}
	o.CopyFrom(m)
	return o
}

func (m *CreateVolumeRequest) CopyFrom(src interface{}) {

	o := src.(*CreateVolumeRequest)
	if o.Spec != nil {
		m.Spec = &VolumeSpec{}
		deepcopy.Copy(m.Spec, o.Spec)
	}

}

func (m *CreateVolumeResponse) Copy() *CreateVolumeResponse {
	if m == nil {
		return nil
	}
	o := &CreateVolumeResponse{}
	o.CopyFrom(m)
	return o
}

func (m *CreateVolumeResponse) CopyFrom(src interface{}) {

	o := src.(*CreateVolumeResponse)
	if o.Volume != nil {
		m.Volume = &Volume{}
		deepcopy.Copy(m.Volume, o.Volume)
	}

}

func (m *GetVolumeRequest) Copy() *GetVolumeRequest {
	if m == nil {
		return nil
	}
	o := &GetVolumeRequest{}
	o.CopyFrom(m)
	return o
}

func (m *GetVolumeRequest) CopyFrom(src interface{}) {

	o := src.(*GetVolumeRequest)
	m.VolumeID = o.VolumeID
}

func (m *GetVolumeResponse) Copy() *GetVolumeResponse {
	if m == nil {
		return nil
	}
	o := &GetVolumeResponse{}
	o.CopyFrom(m)
	return o
}

func (m *GetVolumeResponse) CopyFrom(src interface{}) {

	o := src.(*GetVolumeResponse)
	if o.Volume != nil {
		m.Volume = &Volume{}
		deepcopy.Copy(m.Volume, o.Volume)
	}

}

func (m *UpdateVolumeRequest) Copy() *UpdateVolumeRequest {
	if m == nil {
		return nil
	}
	o := &UpdateVolumeRequest{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateVolumeRequest) CopyFrom(src interface{}) {

	o := src.(*UpdateVolumeRequest)
	m.VolumeID = o.VolumeID
	if o.VolumeVersion != nil {
		m.VolumeVersion = &Version{}
		deepcopy.Copy(m.VolumeVersion, o.VolumeVersion)
	}

	if o.Spec != nil {
		m.Spec = &VolumeSpec{}
		deepcopy.Copy(m.Spec, o.Spec)
	}

}

func (m *UpdateVolumeResponse) Copy() *UpdateVolumeResponse {
	if m == nil {
		return nil
	}
	o := &UpdateVolumeResponse{}
	o.CopyFrom(m)
	return o
}

func (m *UpdateVolumeResponse) CopyFrom(src interface{}) {

	o := src.(*UpdateVolumeResponse)
	if o.Volume != nil {
		m.Volume = &Volume{}
		deepcopy.Copy(m.Volume, o.Volume)
	}

}

func (m *ListVolumesRequest) Copy() *ListVolumesRequest {
	if m == nil {
		return nil
	}
	o := &ListVolumesRequest{}
	o.CopyFrom(m)
	return o
}

func (m *ListVolumesRequest) CopyFrom(src interface{}) {

	o := src.(*ListVolumesRequest)
	if o.Filters != nil {
		m.Filters = &ListVolumesRequest_Filters{}
		deepcopy.Copy(m.Filters, o.Filters)
	}

}

func (m *ListVolumesRequest_Filters) Copy() *ListVolumesRequest_Filters {
	if m == nil {
		return nil
	}
	o := &ListVolumesRequest_Filters{}
	o.CopyFrom(m)
	return o
}

func (m *ListVolumesRequest_Filters) CopyFrom(src interface{}) {

	o := src.(*ListVolumesRequest_Filters)
	if o.Names != nil {
		m.Names = make([]string, len(o.Names))
		copy(m.Names, o.Names)
	}

	if o.IDPrefixes != nil {
		m.IDPrefixes = make([]string, len(o.IDPrefixes))
		copy(m.IDPrefixes, o.IDPrefixes)
	}

	if o.Labels != nil {
		m.Labels = make(map[string]string, len(o.Labels))
		for k, v := range o.Labels {
			m.Labels[k] = v
		}
	}

	if o.NamePrefixes != nil {
		m.NamePrefixes = make([]string, len(o.NamePrefixes))
		copy(m.NamePrefixes, o.NamePrefixes)
	}

	if o.Groups != nil {
		m.Groups = make([]string, len(o.Groups))
		copy(m.Groups, o.Groups)
	}

	if o.Drivers != nil {
		m.Drivers = make([]string, len(o.Drivers))
		copy(m.Drivers, o.Drivers)
	}

}

func (m *ListVolumesResponse) Copy() *ListVolumesResponse {
	if m == nil {
		return nil
	}
	o := &ListVolumesResponse{}
	o.CopyFrom(m)
	return o
}

func (m *ListVolumesResponse) CopyFrom(src interface{}) {

	o := src.(*ListVolumesResponse)
	if o.Volumes != nil {
		m.Volumes = make([]*Volume, len(o.Volumes))
		for i := range m.Volumes {
			m.Volumes[i] = &Volume{}
			deepcopy.Copy(m.Volumes[i], o.Volumes[i])
		}
	}

}

func (m *RemoveVolumeRequest) Copy() *RemoveVolumeRequest {
	if m == nil {
		return nil
	}
	o := &RemoveVolumeRequest{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveVolumeRequest) CopyFrom(src interface{}) {

	o := src.(*RemoveVolumeRequest)
	m.VolumeID = o.VolumeID
	m.Force = o.Force
}

func (m *RemoveVolumeResponse) Copy() *RemoveVolumeResponse {
	if m == nil {
		return nil
	}
	o := &RemoveVolumeResponse{}
	o.CopyFrom(m)
	return o
}

func (m *RemoveVolumeResponse) CopyFrom(src interface{}) {}
