// Code generated by protoc-gen-goswarm. DO NOT EDIT.

package api

import (
	deepcopy "github.com/moby/swarmkit/v2/api/deepcopy"
)

func (m *RaftMember) Copy() *RaftMember {
	if m == nil {
		return nil
	}
	o := &RaftMember{}
	o.CopyFrom(m)
	return o
}

func (m *RaftMember) CopyFrom(src interface{}) {

	o := src.(*RaftMember)
	m.RaftID = o.RaftID
	m.NodeID = o.NodeID
	m.Addr = o.Addr
	if o.Status != nil {
		m.Status = &RaftMemberStatus{}
		deepcopy.Copy(m.Status, o.Status)
	}

}

func (m *JoinRequest) Copy() *JoinRequest {
	if m == nil {
		return nil
	}
	o := &JoinRequest{}
	o.CopyFrom(m)
	return o
}

func (m *JoinRequest) CopyFrom(src interface{}) {

	o := src.(*JoinRequest)
	m.Addr = o.Addr
}

func (m *JoinResponse) Copy() *JoinResponse {
	if m == nil {
		return nil
	}
	o := &JoinResponse{}
	o.CopyFrom(m)
	return o
}

func (m *JoinResponse) CopyFrom(src interface{}) {

	o := src.(*JoinResponse)
	m.RaftID = o.RaftID
	if o.Members != nil {
		m.Members = make([]*RaftMember, len(o.Members))
		for i := range m.Members {
			m.Members[i] = &RaftMember{}
			deepcopy.Copy(m.Members[i], o.Members[i])
		}
	}

	if o.RemovedMembers != nil {
		m.RemovedMembers = make([]uint64, len(o.RemovedMembers))
		copy(m.RemovedMembers, o.RemovedMembers)
	}

}

func (m *LeaveRequest) Copy() *LeaveRequest {
	if m == nil {
		return nil
	}
	o := &LeaveRequest{}
	o.CopyFrom(m)
	return o
}

func (m *LeaveRequest) CopyFrom(src interface{}) {

	o := src.(*LeaveRequest)
	if o.Node != nil {
		m.Node = &RaftMember{}
		deepcopy.Copy(m.Node, o.Node)
	}

}

func (m *LeaveResponse) Copy() *LeaveResponse {
	if m == nil {
		return nil
	}
	o := &LeaveResponse{}
	o.CopyFrom(m)
	return o
}

func (m *LeaveResponse) CopyFrom(src interface{}) {}

func (m *ProcessRaftMessageResponse) Copy() *ProcessRaftMessageResponse {
	if m == nil {
		return nil
	}
	o := &ProcessRaftMessageResponse{}
	o.CopyFrom(m)
	return o
}

func (m *ProcessRaftMessageResponse) CopyFrom(src interface{}) {}

func (m *StreamRaftMessageResponse) Copy() *StreamRaftMessageResponse {
	if m == nil {
		return nil
	}
	o := &StreamRaftMessageResponse{}
	o.CopyFrom(m)
	return o
}

func (m *StreamRaftMessageResponse) CopyFrom(src interface{}) {}

func (m *ResolveAddressRequest) Copy() *ResolveAddressRequest {
	if m == nil {
		return nil
	}
	o := &ResolveAddressRequest{}
	o.CopyFrom(m)
	return o
}

func (m *ResolveAddressRequest) CopyFrom(src interface{}) {

	o := src.(*ResolveAddressRequest)
	m.RaftID = o.RaftID
}

func (m *ResolveAddressResponse) Copy() *ResolveAddressResponse {
	if m == nil {
		return nil
	}
	o := &ResolveAddressResponse{}
	o.CopyFrom(m)
	return o
}

func (m *ResolveAddressResponse) CopyFrom(src interface{}) {

	o := src.(*ResolveAddressResponse)
	m.Addr = o.Addr
}

func (m *InternalRaftRequest) Copy() *InternalRaftRequest {
	if m == nil {
		return nil
	}
	o := &InternalRaftRequest{}
	o.CopyFrom(m)
	return o
}

func (m *InternalRaftRequest) CopyFrom(src interface{}) {

	o := src.(*InternalRaftRequest)
	m.ID = o.ID
	if o.Action != nil {
		m.Action = make([]*StoreAction, len(o.Action))
		for i := range m.Action {
			m.Action[i] = &StoreAction{}
			deepcopy.Copy(m.Action[i], o.Action[i])
		}
	}

}

func (m *StoreAction) Copy() *StoreAction {
	if m == nil {
		return nil
	}
	o := &StoreAction{}
	o.CopyFrom(m)
	return o
}

func (m *StoreAction) CopyFrom(src interface{}) {

	o := src.(*StoreAction)
	m.Action = o.Action
	if o.Target != nil {
		switch o.Target.(type) {
		case *StoreAction_Node:
			v := StoreAction_Node{
				Node: &Node{},
			}
			deepcopy.Copy(v.Node, o.GetNode())
			m.Target = &v
		case *StoreAction_Service:
			v := StoreAction_Service{
				Service: &Service{},
			}
			deepcopy.Copy(v.Service, o.GetService())
			m.Target = &v
		case *StoreAction_Task:
			v := StoreAction_Task{
				Task: &Task{},
			}
			deepcopy.Copy(v.Task, o.GetTask())
			m.Target = &v
		case *StoreAction_Network:
			v := StoreAction_Network{
				Network: &Network{},
			}
			deepcopy.Copy(v.Network, o.GetNetwork())
			m.Target = &v
		case *StoreAction_Cluster:
			v := StoreAction_Cluster{
				Cluster: &Cluster{},
			}
			deepcopy.Copy(v.Cluster, o.GetCluster())
			m.Target = &v
		case *StoreAction_Secret:
			v := StoreAction_Secret{
				Secret: &Secret{},
			}
			deepcopy.Copy(v.Secret, o.GetSecret())
			m.Target = &v
		case *StoreAction_Resource:
			v := StoreAction_Resource{
				Resource: &Resource{},
			}
			deepcopy.Copy(v.Resource, o.GetResource())
			m.Target = &v
		case *StoreAction_Extension:
			v := StoreAction_Extension{
				Extension: &Extension{},
			}
			deepcopy.Copy(v.Extension, o.GetExtension())
			m.Target = &v
		case *StoreAction_Config:
			v := StoreAction_Config{
				Config: &Config{},
			}
			deepcopy.Copy(v.Config, o.GetConfig())
			m.Target = &v
		case *StoreAction_Volume:
			v := StoreAction_Volume{
				Volume: &Volume{},
			}
			deepcopy.Copy(v.Volume, o.GetVolume())
			m.Target = &v
		}
	}

}
